version: '3.3'

services:
  postgresql:
    image: postgres:15-bullseye
    container_name: teamwork_postgresql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5435:5432"