name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # or '7.0.x' if 8.0 is unavailable
          include-prerelease: true # Include this if using a preview version

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore Ecommerce/

      - name: Build
        run: dotnet build Ecommerce/ --configuration Release --no-restore

      - name: Run tests
        run: dotnet test Ecommerce/Ecommerce.Tests --configuration Release --no-build --filter "Category!=Integration"
